name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: carlosperate/download-file-action@v1.0.3
      with:
        file-url: "https://www.antlr.org/download/antlr-4.9.1-complete.jar"
        file-name: "antlr-4.9.1-complete.jar"
        location: "/tools/antlr/"
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
