name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore
    - name: Download ANTLR
      run: wget -P /home/runner/work/OptionExpressions/OptionExpressions/tools/antlr/ "https://www.antlr.org/download/antlr-4.9.1-complete.jar"
    - name: Generate lexer
      run: java -jar /home/runner/work/OptionExpressions/OptionExpressions/tools/antlr/antlr-4.9-complete.jar -Dlanguage=CSharp "./Engine/Grammar/ExpressionLexer.g4" -o "./Engine/Generated" -package OptionExpressions.Engine.Generated
    - name: Generate parser
      run: java -jar /home/runner/work/OptionExpressions/OptionExpressions/tools/antlr/antlr-4.9-complete.jar -Dlanguage=CSharp "./Engine/Grammar/ExpressionParser.g4" -o "./Engine/Generated" -package OptionExpressions.Engine.Generated -visitor -no-listener
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
